
import type { StaffMember, StaffRole, Permission } from '@/types';
import { attachPageAccess } from '@/lib/page-access';

export const PERMISSION_MODULES: (keyof Omit<StaffMember['permissions'], 'pageAccess'>)[] = [
  'orders',
  'packingOrders',
  'products',
  'inventory',
  'customers',
  'purchases',
  'expenses',
  'checkPassing',
  'partners',
  'courierReport',
  'courierManagement',
  'staff',
  'settings',
  'analytics',
  'issues',
  'attendance',
  'accounting',
  'marketing',
  'tasks',
  'integrations',
  'pos',
];

export const perm = (create = false, read = false, update = false, del = false): Permission => ({
  create,
  read,
  update,
  delete: del,
});

export const ALL_ACCESS = perm(true, true, true, true);
export const READ_ONLY = perm(false, true, false, false);
export const NO_ACCESS = perm(false, false, false, false);
export const CREATE_READ_UPDATE = perm(true, true, true, false);

export const PRESETS: Record<string, Omit<StaffMember['permissions'], 'pageAccess'>> = {
  SuperAdmin: Object.fromEntries(PERMISSION_MODULES.map((m) => [m, ALL_ACCESS])) as any,
  Admin: Object.fromEntries(PERMISSION_MODULES.map((m) => [m, ALL_ACCESS])) as any,
  'Modarator Manager': {
    orders: CREATE_READ_UPDATE,
    packingOrders: perm(false, true, true, false),
    products: READ_ONLY,
    inventory: READ_ONLY,
    customers: perm(false, true, true, false),
    purchases: READ_ONLY,
    expenses: READ_ONLY,
    checkPassing: READ_ONLY,
    partners: READ_ONLY,
    courierReport: READ_ONLY,
    courierManagement: READ_ONLY,
    staff: CREATE_READ_UPDATE,
    settings: READ_ONLY,
    analytics: READ_ONLY,
    issues: perm(false, true, true, false),
    attendance: READ_ONLY,
    accounting: READ_ONLY,
    marketing: NO_ACCESS,
    tasks: CREATE_READ_UPDATE,
    integrations: NO_ACCESS,
    pos: NO_ACCESS,
  },
  'Project Manager': {
    orders: READ_ONLY,
    packingOrders: READ_ONLY,
    products: READ_ONLY,
    inventory: READ_ONLY,
    customers: READ_ONLY,
    purchases: READ_ONLY,
    expenses: READ_ONLY,
    checkPassing: READ_ONLY,
    partners: READ_ONLY,
    courierReport: READ_ONLY,
    courierManagement: READ_ONLY,
    staff: CREATE_READ_UPDATE,
    settings: READ_ONLY,
    analytics: NO_ACCESS,
    issues: CREATE_READ_UPDATE,
    attendance: READ_ONLY,
    accounting: READ_ONLY,
    marketing: READ_ONLY,
    tasks: CREATE_READ_UPDATE,
    integrations: READ_ONLY,
    pos: READ_ONLY,
  },
  Manager: {
    orders: CREATE_READ_UPDATE,
    packingOrders: ALL_ACCESS,
    products: ALL_ACCESS,
    inventory: ALL_ACCESS,
    customers: ALL_ACCESS,
    purchases: ALL_ACCESS,
    expenses: ALL_ACCESS,
    checkPassing: ALL_ACCESS,
    partners: ALL_ACCESS,
    courierReport: ALL_ACCESS,
    courierManagement: ALL_ACCESS,
    staff: perm(true, true, true, false),
    settings: perm(true, true, true, false),
    analytics: perm(true, true, true, false),
    issues: ALL_ACCESS,
    attendance: ALL_ACCESS,
    accounting: perm(true, true, true, false),
    marketing: READ_ONLY,
    tasks: ALL_ACCESS,
    integrations: ALL_ACCESS,
    pos: ALL_ACCESS,
  },
  Moderator: {
    orders: CREATE_READ_UPDATE,
    packingOrders: perm(false, true, true, false),
    products: READ_ONLY,
    inventory: READ_ONLY,
    customers: perm(false, true, true, false),
    purchases: READ_ONLY,
    expenses: READ_ONLY,
    checkPassing: READ_ONLY,
    partners: READ_ONLY,
    courierReport: READ_ONLY,
    courierManagement: READ_ONLY,
    staff: READ_ONLY,
    settings: READ_ONLY,
    analytics: READ_ONLY,
    issues: perm(false, true, true, false),
    attendance: READ_ONLY,
    accounting: READ_ONLY,
    marketing: NO_ACCESS,
    tasks: CREATE_READ_UPDATE,
    integrations: NO_ACCESS,
    pos: NO_ACCESS,
  },
  Seller: {
    orders: CREATE_READ_UPDATE,
    packingOrders: READ_ONLY,
    products: READ_ONLY,
    inventory: READ_ONLY,
    customers: CREATE_READ_UPDATE,
    purchases: READ_ONLY,
    expenses: READ_ONLY,
    checkPassing: READ_ONLY,
    partners: READ_ONLY,
    courierReport: READ_ONLY,
    courierManagement: READ_ONLY,
    staff: READ_ONLY,
    settings: READ_ONLY,
    analytics: READ_ONLY,
    issues: READ_ONLY,
    attendance: READ_ONLY,
    accounting: READ_ONLY,
    marketing: NO_ACCESS,
    tasks: CREATE_READ_UPDATE,
    integrations: NO_ACCESS,
    pos: NO_ACCESS,
  },
  'Packing Assistant': {
    orders: READ_ONLY,
    packingOrders: perm(false, true, true, false),
    products: READ_ONLY,
    inventory: perm(false, true, true, false),
    customers: READ_ONLY,
    purchases: READ_ONLY,
    expenses: READ_ONLY,
    checkPassing: READ_ONLY,
    partners: READ_ONLY,
    courierReport: READ_ONLY,
    courierManagement: READ_ONLY,
    staff: READ_ONLY,
    settings: READ_ONLY,
    analytics: READ_ONLY,
    issues: READ_ONLY,
    attendance: READ_ONLY,
    accounting: READ_ONLY,
    marketing: NO_ACCESS,
    tasks: CREATE_READ_UPDATE,
    integrations: NO_ACCESS,
    pos: NO_ACCESS,
  },
  'Call Assistant': {
    orders: CREATE_READ_UPDATE,
    packingOrders: READ_ONLY,
    products: READ_ONLY,
    inventory: READ_ONLY,
    customers: perm(false, true, true, false),
    purchases: READ_ONLY,
    expenses: READ_ONLY,
    checkPassing: READ_ONLY,
    partners: READ_ONLY,
    courierReport: READ_ONLY,
    courierManagement: READ_ONLY,
    staff: READ_ONLY,
    settings: READ_ONLY,
    analytics: READ_ONLY,
    issues: READ_ONLY,
    attendance: READ_ONLY,
    accounting: READ_ONLY,
    marketing: NO_ACCESS,
    tasks: CREATE_READ_UPDATE,
    integrations: NO_ACCESS,
    pos: NO_ACCESS,
  },
  'Call Centre Manager': {
    orders: CREATE_READ_UPDATE,
    packingOrders: perm(false, true, true, false),
    products: READ_ONLY,
    inventory: READ_ONLY,
    customers: CREATE_READ_UPDATE,
    purchases: READ_ONLY,
    expenses: READ_ONLY,
    checkPassing: READ_ONLY,
    partners: READ_ONLY,
    courierReport: perm(false, true, true, false),
    courierManagement: perm(false, true, true, false),
    staff: CREATE_READ_UPDATE,
    settings: READ_ONLY,
    analytics: READ_ONLY,
    issues: perm(false, true, true, false),
    attendance: READ_ONLY,
    accounting: READ_ONLY,
    marketing: NO_ACCESS,
    tasks: CREATE_READ_UPDATE,
    integrations: NO_ACCESS,
    pos: NO_ACCESS,
  },
  'Courier Manager': {
    orders: perm(false, true, true, false),
    packingOrders: perm(false, true, true, false),
    products: READ_ONLY,
    inventory: READ_ONLY,
    customers: READ_ONLY,
    purchases: READ_ONLY,
    expenses: READ_ONLY,
    checkPassing: READ_ONLY,
    partners: READ_ONLY,
    courierReport: CREATE_READ_UPDATE,
    courierManagement: CREATE_READ_UPDATE,
    staff: READ_ONLY,
    settings: READ_ONLY,
    analytics: READ_ONLY,
    issues: READ_ONLY,
    attendance: READ_ONLY,
    accounting: READ_ONLY,
    marketing: NO_ACCESS,
    tasks: CREATE_READ_UPDATE,
    integrations: NO_ACCESS,
    pos: NO_ACCESS,
  },
  Partner: {
    orders: READ_ONLY,
    packingOrders: READ_ONLY,
    products: READ_ONLY,
    inventory: READ_ONLY,
    customers: READ_ONLY,
    purchases: perm(false, true, true, false),
    expenses: READ_ONLY,
    checkPassing: READ_ONLY,
    partners: perm(false, true, true, false),
    courierReport: READ_ONLY,
    courierManagement: READ_ONLY,
    staff: READ_ONLY,
    settings: READ_ONLY,
    analytics: READ_ONLY,
    issues: READ_ONLY,
    attendance: READ_ONLY,
    accounting: READ_ONLY,
    marketing: NO_ACCESS,
    tasks: CREATE_READ_UPDATE,
    integrations: NO_ACCESS,
    pos: NO_ACCESS,
  },
  'Vendor/Supplier': {
    orders: READ_ONLY,
    packingOrders: READ_ONLY,
    products: READ_ONLY,
    inventory: READ_ONLY,
    customers: READ_ONLY,
    purchases: perm(false, true, true, false),
    expenses: READ_ONLY,
    checkPassing: READ_ONLY,
    partners: perm(false, true, true, false),
    courierReport: READ_ONLY,
    courierManagement: READ_ONLY,
    staff: READ_ONLY,
    settings: READ_ONLY,
    analytics: READ_ONLY,
    issues: READ_ONLY,
    attendance: READ_ONLY,
    accounting: READ_ONLY,
    marketing: NO_ACCESS,
    tasks: CREATE_READ_UPDATE,
    integrations: NO_ACCESS,
    pos: NO_ACCESS,
  },
  'Cutting Master': {
    orders: NO_ACCESS,
    packingOrders: NO_ACCESS,
    products: NO_ACCESS,
    inventory: NO_ACCESS,
    customers: NO_ACCESS,
    purchases: READ_ONLY,
    expenses: NO_ACCESS,
    checkPassing: NO_ACCESS,
    partners: NO_ACCESS,
    courierReport: NO_ACCESS,
    courierManagement: NO_ACCESS,
    staff: READ_ONLY,
    settings: NO_ACCESS,
    analytics: NO_ACCESS,
    issues: NO_ACCESS,
    attendance: READ_ONLY,
    accounting: NO_ACCESS,
    marketing: NO_ACCESS,
    tasks: CREATE_READ_UPDATE,
    integrations: NO_ACCESS,
    pos: NO_ACCESS,
  },
  Marketer: {
    orders: CREATE_READ_UPDATE,
    packingOrders: perm(false, true, true, false),
    products: READ_ONLY,
    inventory: READ_ONLY,
    customers: perm(false, true, true, false),
    purchases: READ_ONLY,
    expenses: READ_ONLY,
    checkPassing: READ_ONLY,
    partners: READ_ONLY,
    courierReport: READ_ONLY,
    courierManagement: READ_ONLY,
    staff: READ_ONLY,
    settings: READ_ONLY,
    analytics: NO_ACCESS,
    issues: perm(false, true, true, false),
    attendance: READ_ONLY,
    accounting: READ_ONLY,
    marketing: CREATE_READ_UPDATE,
    tasks: CREATE_READ_UPDATE,
    integrations: NO_ACCESS,
    pos: NO_ACCESS,
  },
  'Finance Manager': {
    orders: READ_ONLY,
    packingOrders: NO_ACCESS,
    products: NO_ACCESS,
    inventory: NO_ACCESS,
    customers: NO_ACCESS,
    purchases: perm(false, true, true, false),
    expenses: CREATE_READ_UPDATE,
    checkPassing: CREATE_READ_UPDATE,
    partners: CREATE_READ_UPDATE,
    courierReport: NO_ACCESS,
    courierManagement: NO_ACCESS,
    staff: perm(false, true, true, false),
    settings: NO_ACCESS,
    analytics: READ_ONLY,
    issues: NO_ACCESS,
    attendance: READ_ONLY,
    accounting: CREATE_READ_UPDATE,
    marketing: NO_ACCESS,
    tasks: CREATE_READ_UPDATE,
    integrations: NO_ACCESS,
    pos: NO_ACCESS,
  },
  Custom: Object.fromEntries(PERMISSION_MODULES.map((m) => [m, NO_ACCESS])) as any,
};

export const DEFAULT_PERMISSIONS: StaffMember['permissions'] = attachPageAccess(PRESETS.Custom, 'Custom');

export const PERMISSIONS = PRESETS;

export function getPresetPermissions(role?: string | null): StaffMember['permissions'] {
  const r = role || 'Custom';
  const base = PRESETS[r] || PRESETS.Custom;
  return attachPageAccess(base as any, r);
}
