import type { StaffMember, Permission } from '@/types';
import { attachPageAccess } from '@/lib/page-access';

type PermissionModule = keyof StaffMember['permissions'];

const modules: PermissionModule[] = [
  'orders',
  'packingOrders',
  'products',
  'inventory',
  'customers',
  'purchases',
  'expenses',
  'checkPassing',
  'partners',
  'courierReport',
  'courierManagement',
  'staff',
  'settings',
  'analytics',
  'issues',
  'attendance',
  'accounting',
  'marketing',
  'tasks',
  'integrations',
];

const perm = (create = false, read = false, update = false, del = false): Permission => ({
  create,
  read,
  update,
  delete: del,
});

const allTrue = perm(true, true, true, true);
const readOnly = perm(false, true, false, false);
const noAccess = perm(false, false, false, false);

const presets: Record<string, StaffMember['permissions']> = {
  SuperAdmin: Object.fromEntries(modules.map((m) => [m, allTrue])) as unknown as StaffMember['permissions'],
  Admin: Object.fromEntries(modules.map((m) => [m, allTrue])) as unknown as StaffMember['permissions'],
  'Modarator Manager': {
    orders: perm(true, true, true, false),
    packingOrders: perm(false, true, true, false),
    products: readOnly,
    inventory: readOnly,
    customers: perm(false, true, true, false),
    purchases: readOnly,
    expenses: readOnly,
    checkPassing: readOnly,
    partners: readOnly,
    courierReport: readOnly,
    courierManagement: readOnly,
    staff: perm(true, true, true, false), // read + create + update
    settings: readOnly,
    analytics: readOnly,
    issues: perm(false, true, true, false),
    attendance: readOnly,
    accounting: readOnly,
    marketing: noAccess,
    tasks: perm(true, true, true, false),
    integrations: noAccess,
  },
  'Project Manager': {
    orders: readOnly,
    packingOrders: readOnly,
    products: readOnly,
    inventory: readOnly,
    customers: readOnly,
    purchases: readOnly,
    expenses: readOnly,
    checkPassing: readOnly,
    partners: readOnly,
    courierReport: readOnly,
    courierManagement: readOnly,
    staff: perm(true, true, true, false), // read + create + update
    settings: readOnly,
    analytics: noAccess,
    issues: perm(true, true, true, false),
    attendance: readOnly,
    accounting: readOnly,
    marketing: readOnly,
    tasks: perm(true, true, true, false),
    integrations: readOnly,
  },
  Manager: {
    orders: perm(true, true, true, false),
    packingOrders: perm(true, true, true, true),
    products: perm(true, true, true, true),
    inventory: perm(true, true, true, true),
    customers: perm(true, true, true, true),
    purchases: perm(true, true, true, true),
    expenses: perm(true, true, true, true),
    checkPassing: perm(true, true, true, true),
    partners: perm(true, true, true, true),
    courierReport: perm(true, true, true, true),
    courierManagement: perm(true, true, true, true),
    staff: perm(true, true, true, false), // manage but safer no delete
    settings: perm(true, true, true, false),
    analytics: perm(true, true, true, false),
    issues: perm(true, true, true, true),
    attendance: perm(true, true, true, true),
    accounting: perm(true, true, true, false),
    marketing: readOnly,
    tasks: allTrue,
    integrations: allTrue,
  },
  Moderator: {
    orders: perm(true, true, true, false),
    packingOrders: perm(false, true, true, false),
    products: readOnly,
    inventory: readOnly,
    customers: perm(false, true, true, false),
    purchases: readOnly,
    expenses: readOnly,
    checkPassing: readOnly,
    partners: readOnly,
    courierReport: readOnly,
    courierManagement: readOnly,
    staff: readOnly,
    settings: readOnly,
    analytics: readOnly,
    issues: perm(false, true, true, false),
    attendance: readOnly,
    accounting: readOnly,
    marketing: noAccess,
    tasks: perm(true, true, true, false),
    integrations: noAccess,
  },
  Seller: {
    orders: perm(true, true, true, false),
    packingOrders: readOnly,
    products: readOnly,
    inventory: readOnly,
    customers: perm(true, true, true, false),
    purchases: readOnly,
    expenses: readOnly,
    checkPassing: readOnly,
    partners: readOnly,
    courierReport: readOnly,
    courierManagement: readOnly,
    staff: readOnly,
    settings: readOnly,
    analytics: readOnly,
    issues: readOnly,
    attendance: readOnly,
    accounting: readOnly,
    marketing: noAccess,
    tasks: perm(true, true, true, false),
    integrations: noAccess,
  },
  'Packing Assistant': {
    orders: readOnly,
    packingOrders: perm(false, true, true, false),
    products: readOnly,
    inventory: perm(false, true, true, false),
    customers: readOnly,
    purchases: readOnly,
    expenses: readOnly,
    checkPassing: readOnly,
    partners: readOnly,
    courierReport: readOnly,
    courierManagement: readOnly,
    staff: readOnly,
    settings: readOnly,
    analytics: readOnly,
    issues: readOnly,
    attendance: readOnly,
    accounting: readOnly,
    marketing: noAccess,
    tasks: perm(true, true, true, false),
    integrations: noAccess,
  },
  'Call Assistant': {
    orders: perm(true, true, true, false),
    packingOrders: readOnly,
    products: readOnly,
    inventory: readOnly,
    customers: perm(false, true, true, false),
    purchases: readOnly,
    expenses: readOnly,
    checkPassing: readOnly,
    partners: readOnly,
    courierReport: readOnly,
    courierManagement: readOnly,
    staff: readOnly,
    settings: readOnly,
    analytics: readOnly,
    issues: readOnly,
    attendance: readOnly,
    accounting: readOnly,
    marketing: noAccess,
    tasks: perm(true, true, true, false),
    integrations: noAccess,
  },
  'Call Centre Manager': {
    orders: perm(true, true, true, false),
    packingOrders: perm(false, true, true, false),
    products: readOnly,
    inventory: readOnly,
    customers: perm(true, true, true, false),
    purchases: readOnly,
    expenses: readOnly,
    checkPassing: readOnly,
    partners: readOnly,
    courierReport: perm(false, true, true, false),
    courierManagement: perm(false, true, true, false),
    staff: perm(true, true, true, false), // read + create + update
    settings: readOnly,
    analytics: readOnly,
    issues: perm(false, true, true, false),
    attendance: readOnly,
    accounting: readOnly,
    marketing: noAccess,
    tasks: perm(true, true, true, false),
    integrations: noAccess,
  },
  'Courier Manager': {
    orders: perm(false, true, true, false),
    packingOrders: perm(false, true, true, false),
    products: readOnly,
    inventory: readOnly,
    customers: readOnly,
    purchases: readOnly,
    expenses: readOnly,
    checkPassing: readOnly,
    partners: readOnly,
    courierReport: perm(true, true, true, false),
    courierManagement: perm(true, true, true, false),
    staff: readOnly,
    settings: readOnly,
    analytics: readOnly,
    issues: readOnly,
    attendance: readOnly,
    accounting: readOnly,
    marketing: noAccess,
    tasks: perm(true, true, true, false),
    integrations: noAccess,
  },
  Partner: {
    orders: readOnly,
    packingOrders: readOnly,
    products: readOnly,
    inventory: readOnly,
    customers: readOnly,
    purchases: perm(false, true, true, false),
    expenses: readOnly,
    checkPassing: readOnly,
    partners: perm(false, true, true, false),
    courierReport: readOnly,
    courierManagement: readOnly,
    staff: readOnly,
    settings: readOnly,
    analytics: readOnly,
    issues: readOnly,
    attendance: readOnly,
    accounting: readOnly,
    marketing: noAccess,
    tasks: perm(true, true, true, false),
    integrations: noAccess,
  },
  'Vendor/Supplier': {
    orders: readOnly,
    packingOrders: readOnly,
    products: readOnly,
    inventory: readOnly,
    customers: readOnly,
    purchases: perm(false, true, true, false),
    expenses: readOnly,
    checkPassing: readOnly,
    partners: perm(false, true, true, false),
    courierReport: readOnly,
    courierManagement: readOnly,
    staff: readOnly,
    settings: readOnly,
    analytics: readOnly,
    issues: readOnly,
    attendance: readOnly,
    accounting: readOnly,
    marketing: noAccess,
    tasks: perm(true, true, true, false),
    integrations: noAccess,
  },
  'Cutting Master': {
    orders: noAccess,
    packingOrders: noAccess,
    products: noAccess,
    inventory: noAccess,
    customers: noAccess,
    purchases: readOnly,
    expenses: noAccess,
    checkPassing: noAccess,
    partners: noAccess,
    courierReport: noAccess,
    courierManagement: noAccess,
    staff: readOnly,
    settings: noAccess,
    analytics: noAccess,
    issues: noAccess,
    attendance: readOnly,
    accounting: noAccess,
    marketing: noAccess,
    tasks: perm(true, true, true, false),
    integrations: noAccess,
  },
  Marketer: {
    orders: perm(true, true, true, false),
    packingOrders: perm(false, true, true, false),
    products: readOnly,
    inventory: readOnly,
    customers: perm(false, true, true, false),
    purchases: readOnly,
    expenses: readOnly,
    checkPassing: readOnly,
    partners: readOnly,
    courierReport: readOnly,
    courierManagement: readOnly,
    staff: readOnly,
    settings: readOnly,
    analytics: noAccess,
    issues: perm(false, true, true, false),
    attendance: readOnly,
    accounting: readOnly,
    marketing: perm(true, true, true, false),
    tasks: perm(true, true, true, false),
    integrations: noAccess,
  },
  'Finance Manager': {
    orders: readOnly,
    packingOrders: noAccess,
    products: noAccess,
    inventory: noAccess,
    customers: noAccess,
    purchases: perm(false, true, true, false),
    expenses: perm(true, true, true, false),
    checkPassing: perm(true, true, true, false),
    partners: perm(true, true, true, false),
    courierReport: noAccess,
    courierManagement: noAccess,
    staff: perm(false, true, true, false),
    settings: noAccess,
    analytics: readOnly,
    issues: noAccess,
    attendance: readOnly,
    accounting: perm(true, true, true, false),
    marketing: noAccess,
    tasks: perm(true, true, true, false),
    integrations: noAccess,
  },
};

const customPermissions: StaffMember['permissions'] = attachPageAccess({
  orders: noAccess,
  packingOrders: noAccess,
  products: noAccess,
  inventory: noAccess,
  customers: noAccess,
  purchases: noAccess,
  expenses: noAccess,
  checkPassing: noAccess,
  partners: noAccess,
  courierReport: noAccess,
  courierManagement: noAccess,
  staff: noAccess,
  settings: noAccess,
  analytics: noAccess,
  issues: noAccess,
  attendance: noAccess,
  accounting: noAccess,
  marketing: noAccess,
  tasks: perm(true, true, true, false),
  integrations: noAccess,
}, 'Custom');

// Fallback minimal read-only permissions
export const defaultPermissions: StaffMember['permissions'] = attachPageAccess({
  orders: readOnly,
  packingOrders: readOnly,
  products: readOnly,
  inventory: readOnly,
  customers: readOnly,
  purchases: readOnly,
  expenses: readOnly,
  checkPassing: readOnly,
  partners: readOnly,
  courierReport: readOnly,
  courierManagement: readOnly,
  staff: readOnly,
  settings: readOnly,
  analytics: readOnly,
  issues: readOnly,
  attendance: readOnly,
  accounting: readOnly,
  marketing: readOnly,
  tasks: perm(true, true, true, false),
  integrations: noAccess,
});

export function getPresetPermissions(role?: string | null): StaffMember['permissions'] {
  if (role === 'Custom') return customPermissions;
  if (role && presets[role]) return attachPageAccess(presets[role], role);
  return defaultPermissions;
}
